<template>
  <div id="BlogPost" style="border: 1px solid black;">
      This text was generated by a global Component BlogPost.vue
    </div>
</template>

<script>
export default {

}
</script>

<style>

</style>